brain_two/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from todos.views import TodoListListView
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include("todos.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("todos_list")), name="home",)
]

todos/urls.py
from django.urls import path
from todos.views import (
    TodoItemCreateView,
    TodoListCreateView,
    TodoListDetailView,
    TodoListListView,
    TodoItemUpdateView,
    TodoListDeleteView,
    TodoListUpdateView
)

urlpatterns = [
    path("", TodoListListView.as_view(), name="todos_list"),
    path("<int:pk>/", TodoListDetailView.as_view(), name="todos_details"),
    path("create/", TodoListCreateView.as_view(), name="todos_create"),
    path("<int:pk>/edit/", TodoListUpdateView.as_view(), name="todos_edit"),
    path("<int:pk>/delete/", TodoListDeleteView.as_view(), name="todos_delete"),
    path("items/create/", TodoItemCreateView.as_view(), name="item_create"),
    path("items/<int:pk>/edit/", TodoItemUpdateView.as_view(), name="item_update"),
]

todos/models.py
from django.db import models

# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList",
        related_name= "items",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.task

todos/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from todos.models import TodoItem, TodoList

# Create your views here.
class TodoListListView(ListView):
    model = TodoList
    template_name = "todos/list.html"

class TodoListDetailView(DetailView):
    model = TodoList
    template_name = "todos/details.html"

class TodoListCreateView(CreateView):
    model = TodoList
    template_name = "todos/create.html"
    fields = ["name"]
    success_url = reverse_lazy("todos_list")

class TodoListUpdateView(UpdateView):
    model = TodoList
    template_name = "todos/update.html"
    fields = ["name"]
    success_url = reverse_lazy("todos_list")
    
class TodoListDeleteView(DeleteView):
    model = TodoList
    template_name = "todos/delete.html"
    success_url = reverse_lazy("todos_list")

class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "todos/item_create.html"
    fields = ["task", "due_date", "is_completed", "list"]
    success_url = reverse_lazy("todos_list")

    # def form_valid(self, form):
    #     form.instance.author = self.request.user
    #     return super().form_valid(form)

class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "todos/item_update.html"
    fields = ["task", "due_date", "is_completed", "list"]
    success_url = reverse_lazy("todos_list")

todos/templates/todos/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo List</title>
</head>
<body>
    <header>
        <h1>To-do Lists!</h1>
        <nav>
            <ul>
                <a href="{% url 'todos_create' %}">Create a list!</a>
                <a href="{% url 'item_create' %}">Create Item!</a>
            </ul>
        </nav>
    </header>
    <main> 
        <div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <button>Create</button>
                </div>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/delete.html
<!DOCTYPE html>
<html lang="en">
<body>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Delete?</title>
    </head>
        <h1>To-do Lists!</h1>
        <main>
            <form method="post">
                {% csrf_token %}
                <p>
                    Are you sure you want to delete "{{ todolist }}"?
                </p>
                {{ form.as_p }}
                <div>
                    <button>Delete</button>
                </div>
            </form>
        </main>
</body>
</html>

todos/templates/todos/details.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Details of Todo List</title>
</head>

<body>
    <header>
        <h1>To-do Lists!</h1>
        <a href="{% url 'todos_delete' todolist.id %}">Delete?</a>
        <a href="{% url 'todos_edit' todolist.id %}">Edit?</a>
    </header>
    <main>
        {% for x in todolist.items.all %}
        <div>
            <h2>
                <a href="{% url "item_update" x.id %}">{{ x.name }}</a>
            </h2>
        </div>
        {% endfor %}
    </main>
    <footer>
    </footer>
</body>
</html>

todos/templates/todos/item_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% comment %} <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% endcomment %}
    <title>Todo List</title>
</head>
<body>
    <header>
        <h1>Todo Lists!</h1>
        <nav>
            <ul>
                <a href="{% url 'todos_create' %}">Create a list!</a>
                <a href="{% url 'item_create' %}">Create Item!</a>
            </ul>
        </nav>
    </header>
    <main> 
        <div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <button>Create</button>
                </div>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/item_update.html
<!doctype html>
<html lang="en">
    <head>
        <title>Edit Todo List</title>
    </head>
    <body>
        <h1>Edit {{todoitem.name}}?</h1>
        <main>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <button>Update!</button>
                </div>
            </form>
        </main>
    </body>
</html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% comment %} <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% endcomment %}
    <title>Todo List</title>
</head>
<body>
    <header>
        <h1>{{ todolist.name }}</h1>
        <nav>
            <a href="{% url 'todos_create' %}">Create a list!</a>
            <a href="{% url 'item_create' %}">Create Item!</a>
        </nav>
    </header>
    <main>
    {% for x in todolist_list %}
    <div>
        <h2>
            <a href="{% url "todos_details" x.id %}">{{ x.name }}</a>
        </h2>
    </div>
    {% endfor %}
</body>
</html>

todos/templates/todos/update.html
<!doctype html>
<html lang="en">
    <head>
        <title>Edit Todo List</title>
    </head>
    <body>
        <h1>To-do Lists!</h1>
        <main>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <button>Update!</button>
                </div>
            </form>
        </main>
    </body>
</html>